### ISSUE TITLE
Unable to get to traefik ingress

### ISSUE THREAD

**Issue by META-DREAMER** [k8s-at-home/template-cluster-k3s#206]
# Details

Whenever I try to connect to the ingress IP I get a 522 error. Looking at the traefik helm-release, shouldnt there be 443 and 80 ports open here? Still learning this stuff...

```yml
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
```

**What did you expect to happen:**

I am able to access the hajimari dashboard

**Anything else you would like to add:**

**Additional Information:**
