### ISSUE TITLE
Kustomize build failed on flux-system/apps

### ISSUE THREAD

**Issue by nonkronk** [k8s-at-home/template-cluster-k3s#244]
# Details

**What steps did you take and what happened:**

I couldn't get Traefik to be deployed and got this error on ` flux-system/apps`

![image](https://user-images.githubusercontent.com/29120359/155840816-0b702eeb-b828-49f3-bf43-63720327169c.png)

**What did you expect to happen:**

`flux-systems/apps` to be in `READY=True` state

**Anything else you would like to add:**

It missing `./cluster/apps/default/echo-server/config-pvc.yaml` file. So I created one.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-server-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
```
**Additional Information:**

It worked!

I thought I had accidentally deleted the config-pvc.yaml, but then when I checked this template repo, it's not there as well! or was it?
I don't know if it can only happens to my setup. So, please close this issue if it's not necessary a bug.
