### ISSUE TITLE
Multiple NICs and Calico

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/template-cluster-k3s#311]
# Details

Calico, by default, attaches to the first available internet interface (https://projectcalico.docs.tigera.io/networking/ip-autodetection).

The way around this could be achieve by changing `./provision/ansible/playbooks/templates/calico-installation.yaml.j2` and setting a interface name regex

```yaml
kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: enx.*
```

**Comment by brettinternet** [comment]
Perhaps we could automate this with Ansible using the CIDR for IP detection? https://projectcalico.docs.tigera.io/networking/ip-autodetection

```yaml
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      cidrs:
        - "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('network/prefix') }}" # 192.168.200.0/24
```
