### ISSUE TITLE
Document authorizing flux to your repository over SSH

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/template-cluster-k3s#324]
# Details

**Describe the solution you'd like:**

1. Generate new SSH key:
    ```sh
    ssh-keygen -t ecdsa -b 521 -C "github-deploy-key" -f ./cluster/github-deploy-key -q -P ""
    ```
2. Paste public key: https://github.com/onedr0p/home-ops/settings/keys
3. Create sops secret in `cluster/base/flux-system/github-deploy-key.sops.yaml` with the contents of:
    ```yaml
    # yamllint disable
	apiVersion: v1
	kind: Secret
	metadata:
        name: github-deploy-key
	    namespace: flux-system
	stringData:
        # Contents of: github-deploy-key
	    identity: |
	        -----BEGIN OPENSSH PRIVATE KEY-----
	            ...
	        -----END OPENSSH PRIVATE KEY-----
        # Output of: curl --silent https://api.github.com/meta | jq --raw-output '"github.com "+.ssh_keys[]'
	    known_hosts: |
	        github.com ssh-ed25519 ...
	        github.com ecdsa-sha2-nistp256 ...
	        github.com ssh-rsa ...
    ```
4. Encrypt secret:
    ```sh
    sops --encrypt --in-place ./cluster/base/flux-system/github-deploy-key.sops.yaml
    ```
5. Apply secret to cluster:
    ```sh
    sops -d cluster/base/flux-system/github-deploy-key.sops.yaml | kubectl apply -f -
    ```
6.  Update `cluster/base/flux-system/gotk-sync.yaml`:
    ```yaml
    ---
    apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      interval: 5m0s
      url: ssh://git@github.com/onedr0p/home-ops
      ref:
        branch: main
      secretRef:
        name: github-deploy-key
    ```
7. Commit and push changes
8. Verify git repository is now using SSH:
    ```yaml
    kubectl get gitrepository -n flux-system
    ```
