### ISSUE TITLE
Migrate services using loadBalancerIP to the Metallb annotation

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/template-cluster-k3s#332]
# Details

**Describe the solution you'd like:**

`svc.spec.loadBalancerIP` has been deprecated in k8s 1.24. Metallb now has an annotation to assign a Load Balancer IPs.

https://github.com/metallb/metallb/issues/1182

For example the Traefik HelmRelease I believe will look like this:

```yaml
...
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: |-
          "${METALLB_TRAEFIK_ADDR}"
      spec:
        externalTrafficPolicy: Local
...
```
